#!/bin/sh
#
# 10-postfix-common
#
# Define variables and functions used during container initialization.
#
# Defined in Dockerfile:
# DOCKER_APPL_RUNAS DOCKER_CONF_DIR DOCKER_MAIL_LIB
#
DOCKER_DEFAULT_DOMAIN=${DOCKER_DEFAULT_DOMAIN-example.com}
POSTFIX_VIRT_DOMAIN=${POSTFIX_VIRT_DOMAIN-$DOCKER_CONF_DIR/virt-domains}
POSTFIX_VIRT_MAILBOX=${POSTFIX_VIRT_MAILBOX-$DOCKER_CONF_DIR/virt-users}
POSTFIX_ALIASES=${POSTFIX_ALIASES-$DOCKER_CONF_DIR/aliases}
POSTFIX_REGEXP_ALIASES=${POSTFIX_REGEXP_ALIASES-$DOCKER_CONF_DIR/regexp-aliases}
POSTFIX_SASL_PASSWD=${POSTFIX_SASL_PASSWD-$DOCKER_CONF_DIR/sasl-passwords}
POSTFIX_LDAP_USERS_CF=${POSTFIX_LDAP_USERS_CF-$DOCKER_CONF_DIR/ldap-users.cf}
POSTFIX_LDAP_ALIAS_CF=${POSTFIX_LDAP_ALIAS_CF-$DOCKER_CONF_DIR/ldap-aliases.cf}
POSTFIX_LDAP_GROUPS_CF=${POSTFIX_LDAP_GROUPS_CF-$DOCKER_CONF_DIR/ldap-groups.cf}
POSTFIX_LDAP_EXPAND_CF=${POSTFIX_LDAP_EXPAND_CF-$DOCKER_CONF_DIR/ldap-groups-expand.cf}

#
# Apply envvars
# Some postfix parameters start with a digit and may contain dash "-"
# and so are not legal variable names
#
postfix_apply_envvars() {
	local env_vars="$(export -p | sed -r 's/export ([^=]+).*/\1/g')"
	local lcase_var env_val
	for env_var in $env_vars; do
		lcase_var="$(echo $env_var | tr '[:upper:]' '[:lower:]')"
		if [ "$(postconf -H $lcase_var 2>/dev/null)" = "$lcase_var" ]; then
			env_val="$(eval echo \$$env_var)"
			dc_log 5 "Setting postfix parameter $lcase_var = $env_val"
			postconf $lcase_var="$env_val"
		fi
	done
}

#
# run early to make sure MAIL_DOMAIN is not empty
#
postfix_default_domains() {
	local domains=${MAIL_DOMAIN-$(hostname -d)}
	if [ -z "$domains" ]; then
		export MAIL_DOMAIN=$DOCKER_DEFAULT_DOMAIN
		dc_log 4 "No MAIL_DOMAIN, non FQDN HOSTNAME, so using $MAIL_DOMAIN"
	fi
}

#
# configure domains if we have recipients
#
postfix_setup_domains() {
	local domains=${MAIL_DOMAIN-$(hostname -d)}
	if [ -n "$domains" ] && ([ -n "$MAIL_BOXES" ] || ([ -n "$LDAP_HOST" ] && [ -n "$LDAP_USER_BASE" ] && [ -n "$LDAP_QUERY_FILTER_USER" ])); then
		dc_log 5 "Configuring postfix for domains $domains"
		if [ $(echo $domains | wc -w) -gt 1 ]; then
			for domain in $domains; do
				dc_cond_append $POSTFIX_VIRT_DOMAIN "$domain #domain"
			done
			postconf virtual_mailbox_domains=hash:$POSTFIX_VIRT_DOMAIN
			postmap  hash:$POSTFIX_VIRT_DOMAIN
		else
			postconf mydomain=$domains
			postconf virtual_mailbox_domains='$mydomain'
		fi
	fi
}

#
# Set default postfix alias maps
#
postfix_default_aliasmap() {
	postconf virtual_ldap_alias_maps=
	postconf virtual_regexp_alias_maps=
	postconf 'virtual_alias_maps=$virtual_ldap_alias_maps $virtual_regexp_alias_maps'
}

#
# Setup postfix aliases
# MAIL_ALIASES="alias1:target1a,target1b alias2:target2"
#
postfix_setup_aliasmap() {
	local aliasmaps="${1-$MAIL_ALIASES}"
	if [ -n "$aliasmaps" ]; then
		dc_log 5 "Config. postfix aliases"
		for aliasmap in $aliasmaps; do
			dc_cond_append $POSTFIX_ALIASES $(echo "$aliasmap" | sed 's/[:,]/& /g')
		done
		postconf alias_maps=hash:$POSTFIX_ALIASES
		postconf alias_database=hash:$POSTFIX_ALIASES
		postalias $POSTFIX_ALIASES
		newaliases
	else
		dc_log 7 "No postfix aliases defined"
		postconf alias_maps=
		postconf alias_database=
	fi
}

#
# Allow recipient email address to be rewritten using regexp in REGEX_ALIAS
#
postfix_setup_regex_aliasmap() {
	if [ -n "$REGEX_ALIAS" ]; then
		dc_log 5 "Configuring recipient address rewrite using regexp: $REGEX_ALIAS"
		echo "$REGEX_ALIAS" > $POSTFIX_REGEXP_ALIASES
		postmap $POSTFIX_REGEXP_ALIASES
		postconf "virtual_regexp_alias_maps=regexp:$POSTFIX_REGEXP_ALIASES"
	fi
}

#
# Setup SMTP auth
#
postfix_setup_smtp_auth() {
	local hostauth=${1-$SMTP_RELAY_HOSTAUTH}
	local host=${hostauth% *}
	local auth=${hostauth#* }
	if [ -n "$host" ]; then
		dc_log 5 "Configuring postfix SMTP relay: $host"
		postconf -e relayhost=$host
		if [ -n "$auth" ]; then
			postconf -e smtp_sasl_auth_enable=yes
			postconf -e smtp_sasl_password_maps=hash:$POSTFIX_SASL_PASSWD
			postconf -e smtp_sasl_security_options=noanonymous
			echo "$hostauth" > $POSTFIX_SASL_PASSWD
			postmap hash:$POSTFIX_SASL_PASSWD
		fi
	else
		dc_log 7 "No SMTP relay defined"
	fi
}

#
# Setup ldap mailboxes
#
postfix_setup_mailbox_ldap() {
	if ([ -n "$LDAP_HOST" ] && [ -n "$LDAP_USER_BASE" ] && [ -n "$LDAP_QUERY_FILTER_USER" ]); then
		dc_log 5 "Configuring postfix-ldap with ldap-host $LDAP_HOST"
		postconf virtual_mailbox_maps=ldap:$POSTFIX_LDAP_USERS_CF
		_postfix_generate_ldapmap "$LDAP_USER_BASE" mail "$LDAP_QUERY_FILTER_USER" > $POSTFIX_LDAP_USERS_CF
		if [ -n "$LDAP_QUERY_FILTER_ALIAS" ]; then
			_postfix_generate_ldapmap "$LDAP_USER_BASE" mail "$LDAP_QUERY_FILTER_ALIAS" > $POSTFIX_LDAP_ALIAS_CF
			if [ -n "$LDAP_GROUP_BASE" -a -n "$LDAP_QUERY_FILTER_GROUP" -a -n "$LDAP_QUERY_FILTER_EXPAND" ]; then
				postconf "virtual_ldap_alias_maps=ldap:$POSTFIX_LDAP_ALIAS_CF ldap:$POSTFIX_LDAP_GROUPS_CF ldap:$POSTFIX_LDAP_EXPAND_CF"
				_postfix_generate_ldapmap "$LDAP_GROUP_BASE" memberUid "$LDAP_QUERY_FILTER_GROUP" > $POSTFIX_LDAP_GROUPS_CF
				_postfix_generate_ldapmap "$LDAP_GROUP_BASE" mail "$LDAP_QUERY_FILTER_EXPAND" > $POSTFIX_LDAP_EXPAND_CF
			else
				postconf "virtual_ldap_alias_maps=ldap:$POSTFIX_LDAP_ALIAS_CF"
			fi
		fi
		if [ -z "$VIRTUAL_TRANSPORT" ]; then # need local mail boxes
			mkdir -p $DOCKER_MAIL_LIB
			dc_chowncond $DOCKER_APPL_RUNAS $DOCKER_MAIL_LIB
			postconf virtual_mailbox_base=$DOCKER_MAIL_LIB
			postconf virtual_uid_maps=static:$(id -u $DOCKER_APPL_RUNAS)
			postconf virtual_gid_maps=static:$(id -g $DOCKER_APPL_RUNAS)
		fi
	fi
}

_postfix_generate_ldapmap() {
	local server_host="$LDAP_HOST"
	local search_base="$1"
	local result_attribute="$2"
	local query_filter="$3"
	local bind_dn="$LDAP_BIND_DN"
	local bind_pw="$LDAP_BIND_PW"
	cat <<-!cat
		server_host = $server_host
		search_base = $search_base
		version = 3
		scope = sub
		result_attribute = $result_attribute
		query_filter = $query_filter
	!cat
	if [ -n "$bind_dn" ]; then
	cat <<-!cat
		bind = yes
		bind_dn = $bind_dn
		bind_pw = $bind_pw
	!cat
	fi
}

#
# Setup hash mailboxes
#
postfix_setup_mailbox_hash() {
	local emails="${1-$MAIL_BOXES}"
	if [ -n "$emails" ]; then
		dc_log 5 "Configuring postfix-virt-mailboxes"
		for email in $emails; do
			dc_cond_append $POSTFIX_VIRT_MAILBOX $email $email
		done
#		postconf alias_maps=
#		postconf alias_database=
		postconf virtual_mailbox_maps=hash:$POSTFIX_VIRT_MAILBOX
		postmap hash:$POSTFIX_VIRT_MAILBOX
		if [ -z "$VIRTUAL_TRANSPORT" ]; then # need local mail boxex
			mkdir -p $DOCKER_MAIL_LIB
			dc_chowncond $DOCKER_APPL_RUNAS $DOCKER_MAIL_LIB
			postconf virtual_mailbox_base=$DOCKER_MAIL_LIB
			postconf virtual_uid_maps=static:$(id -u $DOCKER_APPL_RUNAS)
			postconf virtual_gid_maps=static:$(id -g $DOCKER_APPL_RUNAS)
		fi
	fi
}

#
# Update SMTPD_TLS_CERT_FILE and SMTPD_TLS_KEY_FILE.
# Variables defined in 30-acme-common
# DOCKER_APPL_SSL_CERT
# DOCKER_APPL_SSL_KEY
#
postfix_export_tls_cert() {
	if ([ -f $DOCKER_APPL_SSL_CERT ] && [ -f $DOCKER_APPL_SSL_KEY ]); then
		export SMTPD_TLS_CERT_FILE=${SMTPD_TLS_CERT_FILE-$DOCKER_APPL_SSL_CERT}
		export SMTPD_TLS_KEY_FILE=${SMTPD_TLS_KEY_FILE-$DOCKER_APPL_SSL_KEY}
	fi
}

#
# Generate self signed certificate if SMTPD_USE_TLS=yes but no certificates
# are given.
#
postfix_generate_tls_cert() {
	if ([ -z "$SMTPD_TLS_CERT_FILE" ] && [ -z "$SMTPD_TLS_ECCERT_FILE" ] && \
		[ -z "$SMTPD_TLS_DCERT_FILE" ] && [ -z "$SMTPD_TLS_CHAIN_FILES" ] && \
		[ "$SMTPD_USE_TLS" = "yes" ] && dc_is_installed openssl); then
		dc_log 4 "SMTPD_USE_TLS=yes but no certs given, so generating self-signed cert for host $HOSTNAME"
		dc_tls_setup_selfsigned_cert $DOCKER_APPL_SSL_CERT $DOCKER_APPL_SSL_KEY
	fi
}

#
# Activate TLS if we have relevent envvars defined.
#
postfix_activate_tls_cert() {
	if ([ -n "$SMTPD_TLS_CERT_FILE" ] || [ -n "$SMTPD_TLS_ECCERT_FILE" ] || \
		[ -n "$SMTPD_TLS_DCERT_FILE" ] || [ -n "$SMTPD_TLS_CHAIN_FILES" ]); then
		dc_log 5 "Activating incoming tls"
		postconf -e smtpd_use_tls=yes
		postconf -e smtpd_tls_security_level=may
		postconf -e smtpd_tls_auth_only=yes
	fi
}

#
# Optionally generate non-default Postfix SMTP server EDH parameters for improved security.
# Note, since 2015, 512 bit export ciphers are no longer used this takes a long time.
# Run this manually once the container is up by:
# conf postfix_update_dhparam
#
postfix_update_dhparam() {
	local bits=${1-2048}
	if dc_is_installed openssl; then
		dc_log 5 "Regenerating postfix edh $bits bit parameters"
		mkdir -p $DOCKER_APPL_SSL_DIR
		openssl dhparam -out $DOCKER_APPL_SSL_DIR/dh$bits.pem $bits
		postconf smtpd_tls_dh1024_param_file=$DOCKER_APPL_SSL_DIR/dh$bits.pem
	else
		dc_log 4 "Cannot regenerate edh since openssl is not installed"
	fi
}
