#!/bin/sh
#
# 42_postfix_config-all
#
#
#

#
# Config
#
source docker-common.inc
source docker-postfix.inc

#
# Run
#
if dc_need_config; then
	dp_default_domains
	dp_acme_postfix_tls_cert
	dp_amavis_domains
	dp_amavis_dkim
	dp_amavis_apply_envvars
	dp_dovecot_smtpd_auth_pwfile
	dp_postfix_domains
	dp_postfix_smtp_auth_pwfile
	dp_postfix_mailbox_auth_hash
	dp_postfix_mailbox_auth_ldap
	dp_postfix_alias_map
	dp_postfix_generate_tls_cert
	dp_postfix_activate_tls_cert
	dp_postfix_apply_envvars
	dp_razor_register
	dc_lock_config
else
	dl_log 5 "Found config lock file, so not touching configuration"
fi

