#!/bin/sh
#
# 60-postfix-config-late
#
# Functions defined in:
# 10-postfix-common
#
#

#
# Run late.
#
if dc_is_unlocked; then
	postfix_setup_domains
	postfix_setup_smtp_auth
	postfix_setup_mailbox_hash
	postfix_setup_mailbox_ldap
	postfix_setup_aliasmap
	postfix_export_tls_cert
	postfix_generate_tls_cert
	postfix_export_tls_cert
	postfix_activate_tls_cert
	postfix_apply_envvars
fi
dc_lock_config
