#!/bin/sh
#
# 10-dovecot-common
#
# Define variables and functions used during container initialization.
#
# Defined in Dockerfile:
# DOCKER_IMAPPASSWD_FILE
#
dovecot_setup_postfix() {
	local clientauth=${1-$SMTPD_SASL_CLIENTAUTH}
	# dovecot need to be installed
	if (dc_is_installed dovecot && [ -n "$clientauth" ]); then
		dc_log 5 "Enabling postfix-dovecot client SASL via submission"
		# create client passwd file used for autentication
		for entry in $clientauth; do
			dc_cond_append $DOCKER_IMAPPASSWD_FILE $entry
		done
		# enable sasl auth on the submission port
		postconf -M "submission/inet=submission inet n - n - - smtpd"
		postconf -P "submission/inet/syslog_name=postfix/submission"
		postconf -P "submission/inet/smtpd_sasl_auth_enable=yes"
		postconf -P "submission/inet/smtpd_sasl_type=dovecot"
		postconf -P "submission/inet/smtpd_sasl_path=private/auth"
		postconf -P "submission/inet/smtpd_sasl_security_options=noanonymous"
		postconf -P "submission/inet/smtpd_tls_security_level=encrypt"
		postconf -P "submission/inet/smtpd_tls_auth_only=yes"
		postconf -P "submission/inet/smtpd_client_restrictions=permit_sasl_authenticated,reject"
		postconf -P "submission/inet/smtpd_recipient_restrictions=permit_auth_destination,reject"
#		postconf -P "submission/inet/smtpd_recipient_restrictions=reject_non_fqdn_recipient,reject_unknown_recipient_domain,permit_sasl_authenticated,reject"
		postconf -M "smtps/inet=smtps inet n - n - - smtpd"
		postconf -P "smtps/inet/syslog_name=postfix/smtps"
		postconf -P "smtps/inet/smtpd_sasl_auth_enable=yes"
		postconf -P "smtps/inet/smtpd_sasl_type=dovecot"
		postconf -P "smtps/inet/smtpd_sasl_path=private/auth"
		postconf -P "smtps/inet/smtpd_sasl_security_options=noanonymous"
		postconf -P "smtps/inet/smtpd_tls_security_level=encrypt"
		postconf -P "smtps/inet/smtpd_tls_auth_only=yes"
		postconf -P "smtps/inet/smtpd_tls_wrappermode=yes"
		postconf -P "smtps/inet/smtpd_client_restrictions=permit_sasl_authenticated,reject"
		postconf -P "smtps/inet/smtpd_recipient_restrictions=permit_auth_destination,reject"
#		postconf -P "smtps/inet/smtpd_reject_unlisted_recipient=yes"
		if dc_is_installed amavisd-new; then
			postconf -P "submission/inet/cleanup_service_name=pre-cleanup"
			postconf -P "smtps/inet/cleanup_service_name=pre-cleanup"
		fi
	fi
}

#
# Generate encrypted password.
#
doveadm_pw() { doveadm pw -p $1 ;}
