#!/bin/bash
# hooks/build
# $DOCKER_REPO and $DOCKER_TAG are injected into the build environment

echo "hooks/build called with IMAGE_NAME=${DOCKER_REPO}:${DOCKER_TAG}, so we will run:"
printenv

case "${DOCKER_TAG}" in
	smtp*)         bld_target=smtp ;;
	milter*)       bld_target=milter ;;
	dkim*)         bld_target=dkim ;;
	full*|latest*) bld_target=full ;;
	*)
		echo "NOTHING since we do not know how to build with tag=${DOCKER_TAG}"
		exit 1
	;;
esac

echo "docker build --target $bld_target -t ${DOCKER_REPO}:${DOCKER_TAG} ."
docker build --target $bld_target -t ${DOCKER_REPO}:${DOCKER_TAG} .
