#!/bin/sh
#
# 50-docker-update-loglevel
#
# If SYSLOG_LEVEL is not empty update syslog level
#

#
# We can call this script from the command line to update SYSLOG_LEVEL within
# a running container.
#
if [ -t 1 ]; then
	loglevel=${1-$SYSLOG_LEVEL}
else
	loglevel=${SYSLOG_LEVEL-4}
fi
if [ -n "$loglevel" ]; then
	dc_log 5 "Setting syslogd level=$loglevel."
	docker-service.sh "syslogd -nO- -l$loglevel $SYSLOG_OPTIONS"
fi
